#version 1.0 2025.03.01
#
#conda env create -f environment.yml
#
#
#conda update -n base conda
#conda install -n base conda-libmamba-solver
#conda config --set solver libmamba
#
#
#conda env update -f environment.yml --prune
#conda remove --name shu_hh --all
#conda env export > "shu_hh_real.yml"
#
#conda activate shu_hh
#python -m ipykernel install --user --name=shu_hh
#jupyter lab
#jupyter notebook

name: shu_hh
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cdsapi
  - xarray
  - cfgrib
  - gdal
  - scikit-learn
  - pandas
  - seaborn
  - openpyxl
  - matplotlib
  - ipympl
  - numpy
  - scipy
  - xlrd
  - pyarrow
  - fastparquet
  - netcdf4
  - statsmodels
  - cartopy
  - jupyterlab
  - notebook
  - pytest
  - ipykernel
  - pip
  - pip:
    - beautifulsoup4
    - xlwings
    - https://github.com/JosePedroMatos/Tethys-meteoraster/releases/latest/download/meteoraster-2.1-py3-none-any.whl
